language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build main branch only

install: 
  - git clone --branch v8.0.0 https://github.com/next-theme/hexo-theme-next themes/next
  - npm install # 更换主题后最好install一下，本地也出现了网页打不开的问题
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: public